### ISSUE TITLE
Add sort_by query parameter to release API

### ISSUE THREAD

**Issue by preaction** [cpan-testers/cpantesters-api#15]
In order to get the release data in a more useful form, we should add a `sort_by` and `dir` query parameters to the release APIs:

* `/v3/release`
* `/v3/release/dist/:distname`
* `/v3/release/author/:authorname`

The `sort_by` query parameter can have the following values:

* `dist` - Order by the distribution's name
* `version` - Order by distribution versions
* `dist_released` - Order by the distribution's release date

The `dir` query parameter can have the following values:

* `asc` - Sort the list in ascending order
* `desc` - Sort the list in descending order

This will then allow the data dashboard to order the releases better (cpan-testers/cpantesters-web#11).

**Comment by 1nickt** [comment]
Suggest `dir` is ambiguous and would be better as `sort_order`.

**Comment by preaction** [comment]
I ended up adding a `/v3/release/dist/:dist/:version` API that solves this in a different way. Right now, sorting this data isn't a priority, so I'm closing this.
