### ISSUE TITLE
Documentation page has no link to github

### ISSUE THREAD

**Issue by andk** [cpan-testers/cpantesters-api#27]
http://api.cpantesters.org/docs/?url=/v3 has no link to github project but should probably have:

- interested parties could learn more about already reported bugs
- interested parties might just be served well with a ponter where to read the source code
- to reach the developers when the other given address is broken (as it recently was or maybe still is)

**Comment by andk** [comment]
Now that I think more about it, there is a link on the page that says:

``` text
See more at http://cpantesters.org
```

Maybe it would be more appropriate to link to api.cpantesters.org. Then people would also get the link to github.

**Comment by preaction** [comment]
Agreed on all counts. I added some links to Github and the API landing page, and added specific text about where to go with problems. I think I need to upgrade this documentation site, and I might need to get rid of Swagger-UI entirely and go with something better, but that's a different project.

This is fixed and deployed, but it might take a few hours for the Fastly cache to serve the new version. Thanks for the report!
